version: '3.3'
services:
  web:
    container_name: featured_repositories_web
    build: .
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/featured_repositories
    env_file: .env
    environment:
      RAILS_ENV: development
  database:
    image: postgres:12.1
    container_name: featured_repositories_db
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
